name: bdsm_observable_tree
description: MobX Observable wrapper for Bi-directional Sorted Map Tree
version: 0.1.0
homepage: https://github.com/shbumba/bdsm_observable_tree
topics:
  - data-structures
  - collections
  - mobx

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mobx: ^2.5.0
  meta: ^1.9.1
  bdsm_tree:
    git:
      url: https://github.com/shbumba/bdsm_tree.git
      ref: main

dev_dependencies:
  test: ^1.21.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
